[theme]
base = "dark"
primaryColor = "#00FFFF"
backgroundColor = "#080E15"
secondaryBackgroundColor = "#131D26"
textColor = "#FFFFFF"

[client]
showErrorDetails = true

[server]
headless = true
enableCORS = true
enableXsrfProtection = true